### ISSUE TITLE
scitch to Mujoco  pro 1.5

### ISSUE THREAD

**Issue by sosinfo212** [modestyachts/ARS#10]
hello 
i have mujoco 150 and when i run ARS.py file  i got this error 

`Please put your binaries into ~/.mujoco/mjpro131 or set MUJOCO_PY_MJPRO_PATH. Follow the instructions on https://github.com/openai/mujoco-py for setup.')
mujoco_py.error.MujocoDependencyError: Found your MuJoCo license key but not binaries. Please put your binaries into ~/.mujoco/mjpro131 or set MUJOCO_PY_MJPRO_PATH. Follow the instructions on https://github.com/openai/mujoco-py for setup`

**Comment by lmaddira** [comment]
is the problem solved
I'm facing the same issue
