### ISSUE TITLE
can not run the expert policy

### ISSUE THREAD

**Issue by JiahaoYao** [modestyachts/ARS#11]
Hi, 
I run the expert policy `python run_policy.py ../trained_policies/Humanoid-v1/policy_reward_11600/lin_policy_plus.npz Humanoid-v1 --render  --num_rollouts 20` and stuck at the [first few lines](https://github.com/modestyachts/ARS/blob/master/code/run_policy.py#L22-L23). 

I got the error like this: 
```
loading and building expert policy
Traceback (most recent call last):
  File "run_policy.py", line 62, in <module>
    main()
  File "run_policy.py", line 23, in main
    lin_policy = lin_policy.items()[0][1]
TypeError: 'ItemsView' object does not support indexing
``` 

Could anyone tell me how to fix this?

**Comment by huangrenke** [comment]
I have the same problem....

**Comment by Roadsong** [comment]
Try `np.load(something, allow_pickle=True)`

**Comment by JiahaoYao** [comment]
thanks @Roadsong !
