### ISSUE TITLE
Variance is not computed like in blog post by John D. Cook

### ISSUE THREAD

**Issue by tobiasfeil** [modestyachts/ARS#3]
In the aforementioned blog post, one step in computing the variance looks like this:

![image](https://user-images.githubusercontent.com/17533713/41645746-2c74ceec-7472-11e8-96d4-7c31d8fbc5e2.png)

However, in this project, the corresponding step looks like this:

![image](https://user-images.githubusercontent.com/17533713/41645831-6d3a81a6-7472-11e8-8a31-4d6a4a0141c5.png)

Since this
![image](https://user-images.githubusercontent.com/17533713/41645844-77a3544c-7472-11e8-9638-ba28fc5009af.png)

is the mathematical equation corresponding to this computation, it's looking like the blog post implementation is in accordance to the mathematical formulation while this project's implementation is not. Or am I missing something?

Thanks!

**Comment by hmania** [comment]
There are multiple ways of updating the standard deviation online. The blog post is a reference
for how one might do it. We used a different formula. In particular, note that our update term is multiplied by n1 / self._n , while the update in the blog has no such scaling. Also, note that the function "var" returns self._S / (self._n - 1). To see how to derive the formula we used follow the thread [here.](https://math.stackexchange.com/questions/102978/incremental-computation-of-standard-deviation)
