### ISSUE TITLE
assert len(plasma_managers) >= 1 AssertionError

### ISSUE THREAD

**Issue by jp18813100494** [modestyachts/ARS#4]
![default](https://user-images.githubusercontent.com/26135273/42794766-53af1214-89b3-11e8-8c35-ab7fb51ad18a.png)
anyone know how to solve the problem?

**Comment by hmania** [comment]
It looks like you did not start Ray, the distributed execution engine. You first need to 
run the command 

ray start --head --redis-port=6379 --num-workers=18 
(18 or however many workers you want)

If you did run it, the function socket.gethostbyname might not return
the right local_ip address (depending on the system you have).
In that case, you should just copy paste the redis address returned by the 
"ray start" command into the python script.

**Comment by jp18813100494** [comment]
@hmania Thank you very much.I solved my problem at your suggestion!However I met another problem in the next step！Can you help me?
![1](https://user-images.githubusercontent.com/26135273/42800070-c868ae6c-89cc-11e8-8db7-5f408b7a5fdc.png)

**Comment by hmania** [comment]
It looks like you don't have enough memory. You could try giving the "count" variable in line 31 a 
smaller value, which would translate into a smaller shared noise table. Ideally you would want that value large to keep samples independent, but you should see if making it smaller solves your problem.

**Comment by jp18813100494** [comment]
@hmania You are right.I solved the problem by change the variable "count" smaller!
